name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # cooking final PDF
      - name: latex2pdf
  # You may pin to the exact commit or the version.
  # uses: thomas-chauvet/latex2pdf-action@9d5d68988dd384016bff36f2674ba33527cc631a
        uses: thomas-chauvet/latex2pdf-action@1.0.1
        with:
    # Output directory to store the pdf file.
          output_dir: pdf # default is
    # Main latex file to convert in PDF (for intance `cv.tex`).
          main_latex_file: src.tex/Orleanski_Dmitri.CV.tex # default is main.tex
    # "Extra package from CTAN to install. List of packages available [here](http://mirror.ctan.org/systems/texlive/tlnet/archive).
    # Each package must be separated by a space (ex: "moderncv xargs")."
          ctan_packages: colortbl moderncv fontawesome5 luatexbase # optional
