# This is a basic workflow to help you get started with Actions

name: CV.pdf compilation status

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: LaTeX compilation
  # You may pin to the exact commit or the version.
  # uses: dante-ev/latex-action@49cf7cb5f79e7b2006dbdffea85e02bec0b6244b
        uses: dante-ev/latex-action@2021-A
        with:
    # The root LaTeX file to be compiled
            root_file: Orleanski_Dmitri.CV.tex
    # The working directory for the latex compiler to be invoked
            working_directory: src.tex # optional
    # LaTeX engine to be used
            compiler: latexmk # optional, default is latexmk
    # Extra arguments to be passed to the latex compiler
            args: -pdf -latexoption=-file-line-error -latexoption=-interaction=nonstopmode # optional, default is -pdf -latexoption=-file-line-error -latexoption=-interaction=nonstopmode
    # Install extra packages by apt-get
            #extra_system_packages: # optional

    # Загружаем собранные pdf-файлы
      - name: Upload pdf document
        uses: actions/upload-artifact@v2
        with:
        # Это значение используется как ключ в хранилище
            name: Orleanski_Dmitri.CV.pdf
        # Путь до собранного pdf. Может содержать “*”, “**”
        # Здесь это <working_directory>/<jobname>.pdf
            path: src.tex/Orleanski_Dmitri.CV.pdf


      - name: Update Release
  # You may pin to the exact commit or the version.
  # uses: johnwbyrd/update-release@1d5ec4791e40507e5eca3b4dbf90f0b27e7e4979
        uses: johnwbyrd/update-release@v1.0.0
        with:
    # Your Github token; try \$\{\{ secrets.GITHUB_TOKEN \}\} if your build lasts less than an hour, or create your own secret token with repository access if your build requires longer than an hour.
          token:  ${{ secrets.GITHUB_TOKEN }}
    # Paths to built files to be released. May be absolute or relative to \$\{\{ github.workspace \}\}.
          files: pdf\
    # The name of the release to be created. A reasonable looking release name will be created from the current \$\{\{ github.ref \}\} if this input is not supplied.
          release: Orleanski_Dmitri.CV.pdf # optional
    # The name of the tag to be used. If not provided, the name of the release will be used.
          tag: release # optional
    # A one-line description for both the tag and the release.
          message: latest CV # optional
    # A fuller description of the release.
          body: Latest curriculum Vitae  # optional
    # Should the release, if created, be marked as a prerelease?  Such releases are generally publicly visible.
          prerelease: false # optional, default is true
    # Should the release, if created, be marked as a draft?  Such releases are generally not publicly visible.
          draft: false # optional
          
          
